site_utilisateurs:
    resource: "@SiteUtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

site_back_office:
    resource: "@SiteBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

site_front_office:
    resource: "@SiteFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"