<?php

namespace Site\BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomersBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersBasketRepository extends EntityRepository
{
}
