<?php

namespace Site\BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaSpecialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaSpecialsRepository extends EntityRepository
{
}
