<?php

namespace Site\BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p');
         $qb->where('p.id IN (:array)');
         $qb->setParameter('array', $array);
         return $qb->getQuery()->getResult();

    }
    
    public function myFind($categoryId)
    {
        
        $query = $this->_em->createQuery('SELECT Prod FROM SiteBackOfficeBundle:Products  Prod WHERE NOT EXISTS (SELECT Spec FROM SiteBackOfficeBundle:Specials Spec WHERE Spec.product = Prod.id) AND Prod.category = :categoryId');
        $query->setParameter('categoryId', $categoryId);
        return $query->getResult();
    }
    
}
