<?php

namespace Site\BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialsRepository extends EntityRepository
{
}
