media:
    path:     /
    defaults: { _controller: "SiteBackOfficeBundle:Media:index" }

media_show:
    path:     /{id}/show
    defaults: { _controller: "SiteBackOfficeBundle:Media:show" }

media_new:
    path:     /new
    defaults: { _controller: "SiteBackOfficeBundle:Media:new" }

media_create:
    path:     /create
    defaults: { _controller: "SiteBackOfficeBundle:Media:create" }
    requirements: { _method: post }

media_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteBackOfficeBundle:Media:edit" }

media_update:
    path:     /{id}/update
    defaults: { _controller: "SiteBackOfficeBundle:Media:update" }
    requirements: { _method: post|put }

media_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteBackOfficeBundle:Media:delete" }
    requirements: { _method: post|delete }
